---

- name: "Making sure lxd containers are present (create and start otherwise)"
  local_action:
    module: "lxd_container"
    name: "{{ item.name }}"
    state: started
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      protocol: lxd
      alias: "{{ item.image }}"
    profiles: ["default"]
    wait_for_ipv4_addresses: true
    timeout: 600
  with_items: "{{ lxd_provisioning_inventory }}"
  when: ((item.name is defined and item.name|trim) and
         (item.image is defined and item.image|trim))

- name: "Making sure we can use the lxd connector on newly created containers"
  local_action: add_host name="{{ item.name }}" ansible_connection=lxd ansible_become=false
  with_items: "{{ lxd_provisioning_inventory }}"
  when: (item.name is defined and item.name|trim)

# TODO the raw case statement below was tested only against Ubuntu, Gentoo and Fedora, other distros are guess work for now.
# Inspired by https://github.com/ansible/ansible/blob/22b10a8f6e928fcfbd23a22e4a63a7f53177fa76/lib/ansible/module_utils/facts.py
- name: "Making sure all debian based containers have python installed"
  delegate_to: "{{ item.name }}"
  raw: "case `cat /etc/os-release | grep '^NAME=' | cut -c7- | sed 's/.$//'` in Ubuntu|Debian) [[ `dpkg -s python` ]] || apt-get install -y python ;; Gentoo) emerge -u python ;; Fedora|CentOS|RedHat|'Oracle Linux') yum install -y python ;; esac"
  with_items: "{{ lxd_provisioning_inventory }}"
  when: (item.name is defined and item.name|trim)

- name: "Updating the inventory"
  become: yes
  lineinfile: dest=/etc/ansible/hosts regexp="^{{ item.name }} ansible_connection=lxd" insertafter="^\[lxd\]" line="{{ item.name }} ansible_connection=lxd"
  with_items: "{{ lxd_provisioning_inventory }}"
  when: (item.name is defined and item.name|trim)
